version: '3.8'
services:
  url-status-checker:
    image: igoralcantara/app:creator-v0.03
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - minha_rede
networks:
  minha_rede:
    external: true
